### ISSUE TITLE
Cobalt-60 - Decay Chain

### ISSUE THREAD

**Issue by danieldjewell** [alexmalins/radioactivedecay#7] opened 2020-11-13 18:57 UTC
I'm still investigating this but I just tested the library with Co-60 and I think something is missing... 

I'm assuming that [this graphic of the Co-60 decay chain](https://commons.wikimedia.org/wiki/File:Cobalt-60m-decay.svg) is accurate - displayed below. 

- Co-60 decays via β<sup>-</sup> to an activated Ni-60 atom which *then* decays via γ to stable Ni-60. (Perhaps we need a new moniker for the intermediate state - it's not labelled as "metastable" but then again, there is an intermediate step which instantaneously(?) decays?.) 
- Currently, ```Radionuclide('Co-60').decay_modes()``` indicates ```['β-']``` -- which is true, but it leaves out the γ emissions.
- I'm not sure if this is a dataset problem or what... Wanted to bring it to your attention :) 

<img src="https://upload.wikimedia.org/wikipedia/commons/0/03/Cobalt-60m-decay.svg" width="80%" />

**Comment by alexmalins** [comment] 2020-11-14 07:28
@danieldjewell Yes, you are quite right about the way Co-60 decays. The β- decays create excited nuclear states of Ni-60, which then de-excite producing γ emissions to reach the ground state. You can see that the Ni-60 excited states have half-lives on the order of a [picosecond](https://www.nndc.bnl.gov/nudat2/getdatasetClassic.jsp?nucleus=60NI&unc=nds), so their de-excitations, although not strictly instant, occur extremely quickly.

The very short-lived excited nuclear states in decay schemes are not usually treated as separate intermediate steps in decay chain modelling. This is because the decays are generally so fast they can be considered practically as instant, and some decay steps pass through 10s of excited states (e.g. [Ac-223 to Fr-219](https://www.nndc.bnl.gov/nudat2/getdecayscheme.jsp?nucleus=219FR&dsid=223ac%20a%20decay&unc=nds)), so labeling each state separately as a metastable state causes things to get unwieldy very quickly.

In practice a cut-off half-life is chosen to split between the very short-lived excited states for which we do not care about the activities, and the longer-lived excited states that we want to treat as proper metastable intermediate steps. ICRP-38 defined a half-life cut-off of 1 minute for this, so any excited nuclear states in decay steps with half-lives longer than 1 min became metastable states proper and were labelled by appending 'm', 'n' etc. to the mass number. ICRP-107 also followed this convention, but also added a few more metastable stables with half-lives between 1 s to 1 min for technical reasons. You can read more about this on page 4 of [JAERI-1347](https://jopss.jaea.go.jp/pdfdata/JAERI-1347.pdf).

A separate but related issue then is `radioactivedecay` reporting the decay mode of Co-60 as `['β-']`. You are right that this is somewhat confusing as it does not immediately indicate to users that there are also γ rays from this decay. The issue is one of convention for how ICRP-107 labels the decay modes - it just uses α, β-, β+, EC, IT & SF to identify the decay pathway of the parent initiating the decay. It does not idicated all the types of radiations emitted from the decay (which, by the above convention, can include subsequent de-excitations of an excited daughter nucleus).

I don't think the right thing to do is to change how `radioactivedecay` reports the decay modes or try to manually relabel then in the ICRP-107 (too much work!). But I will write some sections in the [documentation](https://alexmalins.com/radioactivedecay/) to make it clear what the decay mode labels refer to - and to warn that they do not necessarily indicate all the radiation emissions from the decay.

**Comment by alexmalins** [comment] 2020-11-24 04:17
@danieldjewell The updated [docs](https://alexmalins.com/radioactivedecay/tutorial.html) and doc strings in release 0.0.9's code now highlight that the decay mode string is not a list of all the radiations released by the decay.

**Comment by alexmalins** [comment] 2021-01-07 03:20
Closing this off.

**Closed by alexmalins** 2021-01-07 03:20 UTC
