### ISSUE TITLE
[Feature/Design] Allow Radionuclide objects to be added to Inventory (and/or make all Inventory members Rn objects)

### ISSUE THREAD

**Issue by danieldjewell** [alexmalins/radioactivedecay#6] opened 2020-11-13 18:44 UTC
I really like where this is going!

Had a thought: I tried to add an instantiated Radionuclide object to an Inventory but, as you know, couldn't... It would be nice to be able to add instances of Radionuclide objects directly to inventories... Which then led to the thought that perhaps *all* members of an Inventory collection should be instances of Radionuclide objects? 

Making all Inventory members instances of Radionuclide would have certain advantages: 

- Able to access data properties (e.g. half life, etc.) of isotopes/elements from an Inventory object (**especially** after running ```decay(...)```) without having to separately instantiate a Radionuclide object to access that data 
- Would allow for adding Radionuclide objects directly 
- Would not require a change to existing instantiation for Inventories (if the key to the contents dict is already a Radionuclide object, just use that -- otherwise, if a string, just instantiate a new Radionuclide object transparently) 
- A brief review of ```Inventory.decay()``` looks like it wouldn't take too much to modify? 

(Side note: Since Python 3.6+ is required -- adding [typing/type hints](https://docs.python.org/3/library/typing.html) would be great when using Jupyter/an IDE :) )

Just a thought :)

**Comment by alexmalins** [comment] 2020-11-14 07:36
@danieldjewell Hi Daniel, thanks you - these are very thoughtful suggestions. Yes having Radionuclides objects as members of an Inventory object logically makes a lot of sense and is something I have thought about before. Let me consider your suggestions for a short while before putting forward a plan.

Best wishes,
Alex

**Comment by alexmalins** [comment] 2020-11-24 04:14
@danieldjewell Ok, release 0.0.9 adds support for supplying `Radionuclide` instances to an `Inventory`. It adds the `Inventory` `half_lives()`, `progeny()`, `branching_fractions()` and `decay_modes()` methods so the decay data can be accessed directly from inventories. It also adds type hints.

Currently `Inventory` is not a collection of `Radionuclide` instances, however. The problem is that storing `Radionuclide` instances in `Inventory` as keys within the `contents` dictionary would require that the `Radionuclide` objects are immutable (i.e. they cannot be changed after they are instantiated). This didn't seem like a step forward.

Maybe in a future release an activity attribute can be added to `Radionuclide`, and then store the contents of an `Inventory` as a list of `Radionuclide` instances (moving away from dictionary storage). This is perhaps to best way forward. The current dictionary-based API for users would be kept just for interfacing with `Inventory` objects.

Thanks again for the suggestions.

**Comment by alexmalins** [comment] 2021-01-07 03:20
Closing this off now.

**Closed by alexmalins** 2021-01-07 03:20 UTC
